version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pg-counter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: counter
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  app:
    build: .
    container_name: counter-service
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/counter?sslmode=disable
      PORT: ":3000"
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pgdata:
